# Generated by Django 3.2.8 on 2022-02-06 16:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220206_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimage',
            name='image',
            field=models.ImageField(null=True, upload_to=users.models.upload_to, verbose_name='testImage'),
        ),
    ]
