# Generated by Django 3.2.8 on 2022-02-10 06:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_testimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprofile',
            name='image',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to=users.models.upload_to_profile, verbose_name='image_profile'),
        ),
    ]
