# Generated by Django 3.2.8 on 2022-01-31 03:20

import core.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('language', models.CharField(choices=[('english', 'english'), ('thai', 'thai')], max_length=10)),
                ('price', models.CharField(max_length=3)),
                ('originalPrice', models.CharField(max_length=3)),
                ('isbn', models.CharField(max_length=10)),
                ('pageNumber', models.CharField(max_length=3)),
                ('slug', models.SlugField(max_length=100)),
                ('quantity', models.CharField(max_length=3)),
                ('imgProduct', models.ImageField(upload_to=core.models.upload_to, verbose_name='ImgProduct')),
                ('author', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceNo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestImage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.upload_to2, verbose_name='Test2')),
            ],
        ),
    ]
