# Generated by Django 3.2.8 on 2022-02-12 10:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='imgProduct2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.imageProduct2, verbose_name='imageProduct2'),
        ),
    ]
